const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const backdrop = $('#modalBackdrop');
const modalContent = $('#modalContent');
let toastTimer;
let currentAsset = 'بیت‌کوین';
let orderSide = 'buy';
let balanceHidden = false;
const connectedExchanges = new Map();
const providerSupport = new Map();
let providerStatusLoaded=false;
let authState = {authenticated:false, csrfToken:null};
let featureStates = new Map();
let featureStatusLoaded = false;
const featureLabels = {aiAnalysis:'تحلیل هوشمند',exchangeConnections:'اتصال صرافی',liveTrading:'معامله واقعی',automation:'معامله‌گر خودکار',marketExplorer:'کاوش بازار',activityExport:'خروجی تاریخچه'};
const exchangeOptions = [
  {id:'binance', name:'Binance', region:'بین‌المللی', color:'gold'},
  {id:'okx', name:'OKX', region:'بین‌المللی', color:'white'},
  {id:'kucoin', name:'KuCoin', region:'بین‌المللی', color:'green'},
  {id:'nobitex', name:'نوبیتکس', region:'ایران', color:'violet'},
  {id:'wallex', name:'والکس', region:'ایران', color:'blue'},
  {id:'bitpin', name:'بیت‌پین', region:'ایران', color:'pink'}
];
let balance = 24850000;
const assets = {
  btc: {name:'بیت‌کوین', ticker:'BTC / USDT', price:'۶۷,۴۲۸٫۵۰', icon:'₿', cls:'btc'},
  eth: {name:'اتریوم', ticker:'ETH / USDT', price:'۳,۵۲۱٫۱۸', icon:'◆', cls:'eth'},
  gold:{name:'طلای ۱۸ عیار',ticker:'GOLD / IRR',price:'۳,۴۸۲,۰۰۰',icon:'Au',cls:'gold'},
  sol: {name:'سولانا',ticker:'SOL / USDT',price:'۱۸۲٫۴۰',icon:'◎',cls:'sol'}
};
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2700)}
function openModal(html){modalContent.innerHTML=html;backdrop.classList.add('show');document.body.style.overflow='hidden';const input=$('input',modalContent);if(input) setTimeout(()=>input.focus(),80)}
function closeModal(){backdrop.classList.remove('show');document.body.style.overflow=''}
function apiHeaders(jsonBody=true){return {...(jsonBody?{'Content-Type':'application/json'}:{}),'Accept':'application/json',...(authState.csrfToken?{'X-CSRF-Token':authState.csrfToken}:{})}}
async function refreshAuth(){try{const response=await fetch('/api/auth/session',{cache:'no-store'});if(!response.ok)throw new Error();authState=await response.json();return authState.authenticated===true}catch{authState={authenticated:false,csrfToken:null};return false}}
function makeUUID(){if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID();return'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)})}
function loginModal(afterLogin){openModal(`<div class="modal-symbol ai-icon">♙</div><h2 id="modalTitle">ورود امن Vexon</h2><p class="modal-subtitle">حساب مدیر سرور را وارد کنید تا مدیریت اتصال صرافی فعال شود.</p><div class="form-group"><label for="loginUsername">نام کاربری</label><input id="loginUsername" autocomplete="username" /></div><div class="form-group"><label for="loginPassword">گذرواژه</label><input id="loginPassword" type="password" autocomplete="current-password" /></div><div class="modal-note safe">ورود با کوکی HttpOnly و نشست کوتاه‌مدت انجام می‌شود. از رمز منحصربه‌فرد استفاده کنید.</div><button class="primary-button" id="doLogin">ورود</button><button class="secondary-button" id="cancelModal">انصراف</button>`);$('#cancelModal').onclick=closeModal;$('#doLogin').onclick=async()=>{const button=$('#doLogin');button.disabled=true;try{const response=await fetch('/api/auth/login',{method:'POST',headers:apiHeaders(),body:JSON.stringify({username:$('#loginUsername').value,password:$('#loginPassword').value})});const result=await response.json();if(!response.ok)throw new Error(result.message||'ورود ناموفق بود.');authState=result;closeModal();showToast('ورود امن انجام شد.');if(afterLogin)afterLogin();else loadExchangeStatuses()}catch(error){showToast(error.message||'سرور ورود در دسترس نیست.');button.disabled=false;$('#loginPassword').value=''}}}
$('#modalClose').addEventListener('click',closeModal);
backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
async function loadFeatureStatuses(){try{const response=await fetch('/api/features',{cache:'no-store'});if(!response.ok)return false;const data=await response.json();featureStates=new Map((data.features||[]).map(feature=>[feature.id,feature]));featureStatusLoaded=true;return true}catch{return false}}
async function requireFeature(id,callback){if(!featureStatusLoaded)await loadFeatureStatuses();const feature=featureStates.get(id);if(!featureStatusLoaded||!feature){showToast('وضعیت قابلیت از سرور بررسی نشد؛ دوباره تلاش کنید.');return false}if(!feature.locked||feature.unlocked){callback();return true}accessCodeModal(id,callback);return false}
function accessCodeModal(id,callback){const label=featureLabels[id]||id;openModal(`<div class="modal-symbol ai-icon">🔒</div><h2 id="modalTitle">قابلیت قفل‌شده</h2><p class="modal-subtitle">برای استفاده از <b>${label}</b> کلید ورود را وارد کنید.</p><div class="form-group"><label for="featureAccessCode">کلید ورود</label><input id="featureAccessCode" autocomplete="one-time-code" placeholder="VEX-…" /></div><button class="primary-button" id="unlockFeature">تأیید کلید</button><a class="telegram-link" href="https://t.me/dmj74">برای دریافت کلید ورود به تلگرام dmj74 بروید <span>↗</span></a><div class="modal-note">کلید محدود به همین قابلیت و مدت/تعداد استفاده‌ای است که مدیر تعیین کرده است.</div><button class="secondary-button" id="cancelModal">بستن</button>`);$('#cancelModal').onclick=closeModal;$('#unlockFeature').onclick=async()=>{const code=$('#featureAccessCode').value.trim();if(!code){showToast('کلید ورود را وارد کنید.');return}const button=$('#unlockFeature');button.disabled=true;try{const response=await fetch('/api/features/unlock',{method:'POST',headers:apiHeaders(),body:JSON.stringify({feature:id,code})});const result=await response.json();if(!response.ok||!result.unlocked)throw new Error(result.message||'کلید معتبر نیست.');await loadFeatureStatuses();closeModal();showToast('قابلیت با موفقیت باز شد.');callback()}catch(error){showToast(error.message||'کلید ورود معتبر نیست.');button.disabled=false;$('#featureAccessCode').value=''}}}
async function loadProviderSupport(){if(!featureStatusLoaded)loadFeatureStatuses();try{const response=await fetch('/api/providers',{cache:'no-store'});if(!response.ok)return;const data=await response.json();(data.providers||[]).forEach(p=>providerSupport.set(p.id,p.supported===true));providerStatusLoaded=true}catch{}}
function exchangeModal(){
  const cards=exchangeOptions.map(x=>{const supported=providerSupport.get(x.id);const unavailable=providerStatusLoaded&&supported!==true;const connected=connectedExchanges.has(x.id);return `<button class="exchange-card" data-provider="${x.id}" ${unavailable?'disabled title="آداپتور امن این صرافی هنوز در بک‌اند نصب نیست"':''}><span class="exchange-logo ${x.color}">${x.name==='Binance'?'B':x.name==='OKX'?'OK':x.name==='KuCoin'?'K':x.name==='نوبیتکس'?'ن':'و'}</span><span class="exchange-info"><b>${x.name}</b><small>${x.region}</small></span><span class="exchange-state ${connected?'connected':''} ${unavailable?'unsupported':''}">${unavailable?'به‌زودی':connected?'متصل':'اتصال'}</span></button>`}).join('');
  openModal(`<div class="modal-symbol ai-icon">⌘</div><h2 id="modalTitle">اتصال به صرافی‌ها</h2><p class="modal-subtitle">پیش از شروع معامله، حساب یک یا چند صرافی را متصل کنید.</p><div class="exchange-grid">${cards}</div><div class="exchange-count">${connectedExchanges.size} صرافی متصل <span>· دسترسی برداشت باید خاموش باشد</span></div><div class="modal-note">اتصال پس از ورود امن و تأیید API در سرور انجام می‌شود. این رابط کلیدها را ذخیره نمی‌کند؛ سرویس باید با HTTPS و تنظیمات مدیر فعال باشد. دسترسی صرافی‌ها بسته به کشور و قوانین محل اقامت متفاوت است؛ شرایط رسمی را بررسی کنید.</div><button class="secondary-button" id="cancelModal">بستن</button>`);
  $$('.exchange-card',modalContent).forEach(card=>card.onclick=()=>connectedExchanges.has(card.dataset.provider)?disconnectExchange(card.dataset.provider):exchangeCredentials(card.dataset.provider));
  $('#cancelModal').onclick=closeModal;
}
async function disconnectExchange(id){const exchange=exchangeOptions.find(x=>x.id===id);if(!exchange||!confirm(`اتصال ${exchange.name} قطع و کلید رمز‌شده از سرور حذف شود؟`))return;try{if(!await refreshAuth())throw new Error('auth');const response=await fetch(`/api/exchanges/${encodeURIComponent(id)}`,{method:'DELETE',headers:apiHeaders(false)});if(!response.ok)throw new Error('disconnect');connectedExchanges.delete(id);exchangeModal();renderConnectionStatus();showToast('کلید رمز‌شده از سرور حذف شد.')}catch{showToast('قطع اتصال انجام نشد؛ وضعیت سرور را بررسی کنید.')}}
function exchangeCredentials(id){
  const exchange=exchangeOptions.find(x=>x.id===id);if(!exchange)return;
  const needsPass=['kucoin','okx'].includes(id);
  openModal(`<button class="back-link" id="exchangeBack">← بازگشت به صرافی‌ها</button><div class="modal-symbol ai-icon">⌘</div><h2 id="modalTitle">اتصال ${exchange.name}</h2><p class="modal-subtitle">کلید API با مجوز مشاهده موجودی و معامله اسپات بسازید.</p><div class="form-group"><label for="apiKey">API Key</label><input id="apiKey" autocomplete="off" placeholder="کلید API" /></div><div class="form-group"><label for="apiSecret">API Secret</label><input id="apiSecret" type="password" autocomplete="new-password" placeholder="کلید محرمانه" /></div>${needsPass?'<div class="form-group"><label for="apiPassphrase">عبارت امنیتی (Passphrase)</label><input id="apiPassphrase" type="password" autocomplete="new-password" placeholder="Passphrase صرافی" /></div>':''}<div class="permission-box"><b>مجوزهای پیشنهادی</b><span>✓ مشاهده موجودی</span><span>✓ معامله اسپات</span><span class="no-withdraw">× برداشت وجه (خاموش)</span></div><div class="modal-note">هرگز مجوز برداشت یا انتقال را فعال نکنید. اتصال واقعی فقط پس از راه‌اندازی بک‌اند امن و تأیید صرافی انجام می‌شود. کلیدها را در پیام یا مخزن کد قرار ندهید.</div><button class="primary-button" id="connectExchange">اتصال امن به ${exchange.name}</button><button class="secondary-button" id="cancelModal">انصراف</button>`);
  $('#exchangeBack').onclick=exchangeModal;$('#cancelModal').onclick=closeModal;
  $('#connectExchange').onclick=async()=>{
    const apiKey=$('#apiKey').value.trim(),apiSecret=$('#apiSecret').value.trim(),passphrase=$('#apiPassphrase')?.value.trim()||'';
    if(!apiKey||!apiSecret||(needsPass&&!passphrase)){showToast('اطلاعات API را کامل کنید.');return}
    const btn=$('#connectExchange');btn.disabled=true;btn.textContent='در حال بررسی سرویس امن…';
    try{
      if(!await refreshAuth()){ $('#apiKey').value='';$('#apiSecret').value='';if($('#apiPassphrase'))$('#apiPassphrase').value='';closeModal();showToast('ابتدا وارد حساب Vexon شوید؛ کلیدهای صرافی پاک شدند.');loginModal(()=>exchangeCredentials(id));return; }
      const health=await fetch('/api/health',{headers:apiHeaders(false),cache:'no-store'});
      if(!health.ok)throw new Error('backend_missing');
      const healthData=await health.json();if(healthData.exchangeConnectionsEnabled!==true)throw new Error('connections_disabled');
      const response=await fetch('/api/exchanges/connect',{method:'POST',headers:apiHeaders(),body:JSON.stringify({exchange:id,apiKey,apiSecret,passphrase,permissions:{read:true,spotTrade:true,withdrawals:false}})});
      const result=await response.json().catch(()=>({}));if(response.status===401)throw new Error('auth_required');if(!response.ok||!result.connected)throw new Error(result.message||'connection_failed');
      connectedExchanges.set(id,{id,name:exchange.name,connectedAt:Date.now()});closeModal();showToast(`${exchange.name} با موفقیت متصل شد.`);renderConnectionStatus();
    }catch(error){
      $('#apiKey').value='';$('#apiSecret').value='';if($('#apiPassphrase'))$('#apiPassphrase').value='';btn.disabled=false;btn.textContent=`اتصال امن به ${exchange.name}`;
      const message=error.message==='backend_missing'?'بک‌اند امن در دسترس نیست؛ کلیدها ارسال یا ذخیره نشدند.':error.message==='connections_disabled'?'اتصال صرافی توسط مدیر سرور غیرفعال است؛ کلیدها ارسال نشدند.':error.message==='auth_required'?'ابتدا وارد حساب Vexon شوید.':'اتصال امن برقرار نشد؛ اطلاعات API پاک شد و ذخیره نشد.';
      showToast(message);
    }
  };
}
function renderConnectionStatus(){const el=$('.market-status');if(el){el.innerHTML=`<i></i> ${connectedExchanges.size?`${connectedExchanges.size} صرافی متصل`:'بازار آزمایشی'}`}}
async function loadExchangeStatuses(){try{const response=await fetch('/api/exchanges',{headers:{'Accept':'application/json'},cache:'no-store'});if(!response.ok)return;const data=await response.json();(data.exchanges||[]).forEach(x=>{if(exchangeOptions.some(o=>o.id===x.id)&&x.connected)connectedExchanges.set(x.id,x)});renderConnectionStatus()}catch{}}
function requireExchangeConnection(){if(connectedExchanges.size)return true;requireFeature('exchangeConnections',exchangeModal);showToast('برای شروع معامله ابتدا یک صرافی را متصل کنید.');return false}
$('#openExchange').onclick=()=>requireFeature('exchangeConnections',exchangeModal);$('#openExchangeTop').onclick=()=>requireFeature('exchangeConnections',exchangeModal);$('#openManagement').onclick=adminManagementModal;
function tradeModal(side='buy',name=currentAsset,featureAuthorized=false){
  if(!featureAuthorized){requireFeature('liveTrading',()=>tradeModal(side,name,true));return}
  if(!requireExchangeConnection())return;
  orderSide=side;currentAsset=name;
  const asset=Object.values(assets).find(x=>x.name===name)||assets.btc;
  const base=asset.ticker.split('/')[0].trim();
  const quote=asset.ticker.split('/')[1]?.trim()||'';
  const options=[...connectedExchanges.values()].map(x=>`<option value="${x.id}">${x.name}</option>`).join('');
  openModal(`<h2 id="modalTitle">ثبت سفارش ${side==='buy'?'خرید':'فروش'}</h2><p class="modal-subtitle">${asset.name} · ${asset.ticker} · قیمت تابلو فعلی نمایشی است</p><div class="trade-tabs"><button class="${side==='buy'?'active buy':''} buy-side">خرید</button><button class="${side==='sell'?'active sell':''} sell-side">فروش</button></div><div class="form-group"><label for="orderExchange">صرافی متصل</label><select id="orderExchange">${options}</select></div><div class="form-group"><label for="orderAmount">مقدار ${base}</label><input id="orderAmount" type="number" min="0.00000001" step="any" inputmode="decimal" placeholder="مقدار دارایی" /></div><div class="form-group"><label for="orderPrice">قیمت هر ${base} به ${quote}</label><input id="orderPrice" type="number" min="0.00000001" step="any" inputmode="decimal" placeholder="قیمت محدود موردنظر" /></div><div class="order-summary"><span>نوع سفارش</span><b>محدود (Limit) · اسپات</b></div><div class="order-summary"><span>اجرا</span><b>قیمت تضمین نیست؛ سفارش ممکن است باز بماند</b></div><label class="live-confirm"><input id="confirmLive" type="checkbox" /> <span>می‌دانم این سفارش با پول واقعی ارسال می‌شود و آن را تأیید می‌کنم.</span></label><button class="primary-button" id="submitOrder">ارسال سفارش واقعی ${side==='buy'?'خرید':'فروش'}</button><div class="modal-note">فقط سفارش محدود اسپات پشتیبانی می‌شود؛ سقف مبلغ، اختلاف قیمت، موجودی و نماد در سرور کنترل خواهد شد. برداشت وجه در این برنامه وجود ندارد.</div>`);
  $('.buy-side').onclick=()=>tradeModal('buy',name);$('.sell-side').onclick=()=>tradeModal('sell',name);
  $('#submitOrder').onclick=async()=>{
    const amount=Number($('#orderAmount').value),price=Number($('#orderPrice').value);
    if(!amount||amount<=0||!price||price<=0){showToast('مقدار و قیمت محدود را وارد کنید.');return}
    if(!$('#confirmLive').checked){showToast('برای ادامه، تأیید سفارش واقعی را علامت بزنید.');return}
    const button=$('#submitOrder');button.disabled=true;button.textContent='در حال اعتبارسنجی سفارش…';
    try{
      if(!await refreshAuth()){closeModal();showToast('نشست منقضی شد؛ دوباره وارد شوید.');loginModal();return}
      const response=await fetch('/api/orders',{method:'POST',headers:apiHeaders(),body:JSON.stringify({exchange:$('#orderExchange').value,symbol:asset.ticker.replaceAll(' ',''),side,type:'limit',amount,price,clientOrderId:makeUUID(),confirmLive:true})});
      const result=await response.json().catch(()=>({}));
      if(response.status===401){closeModal();loginModal();return}
      if(!response.ok||result.status!=='accepted')throw new Error(result.message||'سفارش رد شد.');
      closeModal();showToast(`سفارش به صرافی ارسال شد · ${result.exchangeStatus||'وضعیت نامشخص'} · ${result.orderId||''}`);
    }catch(error){button.disabled=false;button.textContent=`ارسال سفارش واقعی ${side==='buy'?'خرید':'فروش'}`;showToast(error.message||'سرویس معامله در دسترس نیست؛ سفارش ثبت نشد.')}
  };
}
function addActivity(side,name,amount){const symbol=Object.values(assets).find(a=>a.name===name)||assets.btc;const row=document.createElement('div');row.className='activity-row';row.innerHTML=`<span class="activity-symbol ${symbol.cls}">${symbol.icon}</span><div class="activity-title"><b>${side==='buy'?'خرید':'فروش'} ${name}</b><small>همین الان · حساب آزمایشی</small></div><span class="activity-amount ${side==='sell'?'positive-text':''}">${side==='buy'?'−':'+'} ${amount.toLocaleString('fa-IR')} <small>تومان</small></span><span class="activity-badge ${side==='buy'?'buy-badge':'sell-badge'}">${side==='buy'?'خرید':'فروش'}</span>`;$('#activityList').prepend(row)}
$$('[data-trade]').forEach(b=>b.addEventListener('click',()=>tradeModal(b.dataset.trade,b.dataset.name)));
$('#mobileTrade').onclick=()=>tradeModal('buy',currentAsset);
function renderBalance(){const el=$('#totalBalance');el.textContent=balanceHidden?'••••••••':Math.max(0,balance).toLocaleString('fa-IR')}
$('#hideBalance').onclick=()=>{balanceHidden=!balanceHidden;renderBalance();$('#hideBalance').textContent=balanceHidden?'◎':'◉'};
$$('.market-row').forEach(row=>row.addEventListener('click',e=>{if(e.target.closest('button'))return;const a=assets[row.dataset.asset];if(!a)return;$('#chartAsset').textContent=a.name;$('#chartTicker').textContent=a.ticker;$('#chartPrice').textContent=a.price;currentAsset=a.name;$('.asset-select .coin-icon').className='coin-icon '+a.cls;$('.asset-select .coin-icon').textContent=a.icon;$$('.market-row').forEach(r=>r.classList.remove('focused'));row.classList.add('focused')}));
$$('.range-tabs button').forEach(button=>button.onclick=()=>{ $$('.range-tabs button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');showToast(`بازه نمودار: ${button.textContent} · داده نمایشی`) });
$$('.risk-options button').forEach(button=>button.onclick=()=>{$$('.risk-options button').forEach(b=>b.classList.remove('selected'));button.classList.add('selected');showToast(`سطح ریسک روی «${button.dataset.risk}» تنظیم شد.`)});
$('#manualMode').onclick=()=>{setMode('manual')};$('#autoMode').onclick=()=>{setMode('auto')};
function setMode(mode){$('#manualMode').classList.toggle('selected',mode==='manual');$('#autoMode').classList.toggle('selected',mode==='auto');if(mode==='auto'){showToast('حالت خودکار انتخاب شد؛ برای شروع، ربات را فعال کنید.')}else{showToast('حالت دستی فعال شد.')}}
$('#botToggle').onclick=async()=>{const b=$('#botToggle');if(b.classList.contains('on')){try{const response=await fetch('/api/bot/disable',{method:'POST'});if(!response.ok)throw new Error();b.classList.remove('on');b.setAttribute('aria-checked','false');$('#botStatusTitle').textContent='ربات غیرفعال است';$('#botStatusDetail').textContent='کنترل معامله در دست شماست';showToast('ربات متوقف شد.')}catch{showToast('توقف ربات از سرور تأیید نشد؛ وضعیت را در صرافی بررسی کنید.')}return}if(!requireExchangeConnection())return;requireFeature('automation',()=>showToast('فعال‌سازی ربات فقط پس از راه‌اندازی و تأیید سرویس امن ممکن است.'))};
$('#botSettings').onclick=()=>requireFeature('automation',openBotSettings);
function openBotSettings(){openModal(`<h2 id="modalTitle">تنظیمات معامله‌گر</h2><p class="modal-subtitle">قوانین کنترل ریسک را برای حساب آزمایشی تنظیم کنید.</p><div class="form-group"><label>دارایی‌های مجاز</label><select><option>بیت‌کوین، اتریوم و طلا</option><option>فقط رمزارزها</option><option>فقط طلا</option><option>انتخاب دستی دارایی‌ها</option></select></div><div class="form-row"><div class="form-group"><label>حداکثر مبلغ هر سفارش (تومان)</label><input type="number" placeholder="۵۰۰٬۰۰۰" /></div><div class="form-group"><label>حد ضرر روزانه (٪)</label><input type="number" placeholder="۲" /></div></div><div class="modal-note safe">در نسخه نهایی، تنظیمات ربات باید سمت سرور اعمال شوند. ربات این نمونه فقط نمایشی است و معامله واقعی نمی‌کند.</div><button class="primary-button" id="saveBot">ذخیره تنظیمات</button>`);$('#saveBot').onclick=()=>{closeModal();showToast('تنظیمات نمایشی ذخیره شد.')}}
function aiModal(){openModal(`<div class="ai-heading" style="margin-bottom:14px"><span class="ai-icon">✳</span><div><b>تحلیل هوشمند Vexon</b><small>BTC / USDT · بازار آزمایشی</small></div></div><h2 id="modalTitle">چشم‌انداز بازار</h2><p class="modal-subtitle">خلاصه‌ای از شاخص‌های نمایشی برای تصمیم‌گیری آگاهانه‌تر.</p><div class="signal-main"><div><strong>تمایل صعودی · ۷۸٪</strong><p>مومنتوم کوتاه‌مدت مثبت است</p></div><div class="signal-gauge"><svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="25"/><circle class="gauge-progress" cx="32" cy="32" r="25"/></svg><b>۷۸<small>٪</small></b></div></div><div class="modal-note safe">حجم معاملات در ۴ ساعت گذشته ۱۲٪ افزایش داشته. محدوده حمایت نمایشی ۶۶,۸۰۰ و مقاومت ۶۸,۲۰۰ USDT است.</div><p class="modal-subtitle">تحلیل تولیدشده برای نمونه رابط کاربری است؛ داده زنده یا مدل هوش مصنوعی به این نسخه متصل نیست. این توصیه مالی نیست.</p><button class="primary-button" id="closeAnalysis">متوجه شدم</button>`);$('#closeAnalysis').onclick=closeModal}
$('#openAi').onclick=()=>requireFeature('aiAnalysis',aiModal);$('#openAiAnalysis').onclick=()=>requireFeature('aiAnalysis',aiModal);
$('#botInfo').onclick=()=>showToast('ربات در نسخه نمایشی فقط شبیه‌سازی می‌کند.');$('#learnMore').onclick=()=>showToast('Vexon یک نمونه اولیه برای مدیریت هوشمند دارایی است.');$('#allMarkets').onclick=()=>requireFeature('marketExplorer',marketExplorer);$('#activityFilter').onclick=()=>requireFeature('activityExport',exportActivity);$('#securityLink').onclick=e=>{e.preventDefault();settingsModal()};
function marketExplorer(){const rows=Object.entries(assets).map(([id,a])=>`<button class="explore-row" data-market="${id}"><span class="coin-icon ${a.cls}">${a.icon}</span><span><b>${a.name}</b><small>${a.ticker}</small></span><strong>${a.price}</strong><span class="explore-star" data-star="${id}">${getWatchlist().includes(id)?'★':'☆'}</span></button>`).join('');openModal(`<h2 id="modalTitle">کاوش بازارها</h2><p class="modal-subtitle">دارایی را برای مشاهدهٔ نمودار انتخاب کنید؛ ستاره برای افزودن به پیگیری.</p><div class="form-group"><input id="marketSearch" placeholder="جستجوی نام یا نماد" aria-label="جستجوی بازار" /></div><div class="explore-list">${rows}</div><div class="modal-note safe">قیمت‌ها و داده‌های این نسخه نمایشی و غیرزنده هستند.</div>`);$('#marketSearch').oninput=()=>{$$('.explore-row',modalContent).forEach(r=>r.hidden=!r.textContent.toLowerCase().includes($('#marketSearch').value.toLowerCase()))};$$('.explore-row',modalContent).forEach(row=>row.onclick=e=>{if(e.target.closest('[data-star]')){e.stopPropagation();toggleWatchlist(row.dataset.market);e.target.textContent=getWatchlist().includes(row.dataset.market)?'★':'☆';return}selectMarket(row.dataset.market);closeModal()})}
function getWatchlist(){try{return JSON.parse(localStorage.getItem('vexon-watchlist')||'[]')}catch{return[]}}
function toggleWatchlist(id){const list=getWatchlist();localStorage.setItem('vexon-watchlist',JSON.stringify(list.includes(id)?list.filter(x=>x!==id):[...list,id]));showToast(list.includes(id)?'از فهرست پیگیری حذف شد.':'به فهرست پیگیری اضافه شد.')}
function selectMarket(id){const a=assets[id];if(!a)return;currentAsset=a.name;$('#chartAsset').textContent=a.name;$('#chartTicker').textContent=a.ticker;$('#chartPrice').textContent=a.price;$('.asset-select .coin-icon').className='coin-icon '+a.cls;$('.asset-select .coin-icon').textContent=a.icon;$$('.market-row').forEach(r=>r.classList.toggle('focused',r.dataset.asset===id))}
function exportActivity(){const rows=[['نوع','دارایی','زمان','مبلغ'],...$$('.activity-row', $('#activityList')).map(r=>[r.querySelector('.activity-badge')?.textContent||'',r.querySelector('.activity-title b')?.textContent||'',r.querySelector('.activity-title small')?.textContent||'',r.querySelector('.activity-amount')?.textContent||''])];const csv='\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download='vexon-activity.csv';link.click();URL.revokeObjectURL(link.href);showToast('گزارش فعالیت‌ها دانلود شد.')}
async function adminFeaturesModal(){
  if(!await refreshAuth()){loginModal(()=>adminFeaturesModal());return}
  try{
    const [featureResponse,codeResponse]=await Promise.all([fetch('/api/admin/features',{headers:apiHeaders(false),cache:'no-store'}),fetch('/api/admin/access-codes',{headers:apiHeaders(false),cache:'no-store'})]);
    if(featureResponse.status===401||codeResponse.status===401){loginModal(()=>adminFeaturesModal());return}
    const featureData=await featureResponse.json(),codeData=await codeResponse.json();if(!featureResponse.ok||!codeResponse.ok)throw new Error('داده‌های مدیریت قابلیت‌ها بارگذاری نشد.');
    const featureOptions=featureData.features.map(f=>`<option value="${f.id}">${featureLabels[f.id]||f.label}</option>`).join('');
    const lockRows=featureData.features.map(f=>`<label class="feature-lock-row"><span><b>${featureLabels[f.id]||f.label}</b><small>${f.locked?'قفل است · ورود با کد لازم است':'باز است · کد لازم نیست'}</small></span><input type="checkbox" data-feature-lock="${f.id}" ${f.locked?'checked':''}></label>`).join('');
    openModal(`<h2 id="modalTitle">قفل قابلیت‌ها و کدهای ورود</h2><p class="modal-subtitle">قفل هر قابلیت را جداگانه مدیریت و برای آن کد محدود و زمان‌دار تولید کنید.</p><div class="feature-lock-list">${lockRows}</div><button class="primary-button" id="saveFeatureLocks">ذخیرهٔ قفل قابلیت‌ها</button><div class="admin-divider"></div><h3>تولید کد ورود</h3><div class="form-group"><label for="codeFeature">قابلیت</label><select id="codeFeature">${featureOptions}</select></div><div class="form-row"><div class="form-group"><label for="codeExpiry">اعتبار (ساعت)</label><input id="codeExpiry" type="number" min="1" max="8760" value="24" /></div><div class="form-group"><label for="codeUses">حداکثر دفعات استفاده</label><input id="codeUses" type="number" min="1" max="500" value="1" /></div></div><button class="primary-button" id="generateAccessCode">تولید کد یک‌بارنمایش</button><div class="code-result" id="codeResult" hidden></div><div class="admin-divider"></div><h3>کدهای ساخته‌شده</h3><p class="modal-subtitle">مقدار خود کد پس از تولید دوباره نمایش داده نمی‌شود.</p><div class="access-code-list" id="accessCodeList">${renderAdminCodeRows(codeData.codes||[])}</div><button class="secondary-button" id="cancelModal">بستن</button>`);
    $('#cancelModal').onclick=closeModal;
    $('#saveFeatureLocks').onclick=async()=>{const featureLocks=Object.fromEntries($$('[data-feature-lock]',modalContent).map(input=>[input.dataset.featureLock,input.checked]));try{const r=await fetch('/api/admin/features',{method:'POST',headers:apiHeaders(),body:JSON.stringify({featureLocks})});const data=await r.json();if(!r.ok)throw new Error(data.message||'ذخیره قفل‌ها انجام نشد.');await loadFeatureStatuses();showToast('قفل قابلیت‌ها ذخیره شد.');adminFeaturesModal()}catch(error){showToast(error.message||'ذخیره قفل‌ها انجام نشد.')}};
    $('#generateAccessCode').onclick=async()=>{const button=$('#generateAccessCode');button.disabled=true;try{const r=await fetch('/api/admin/access-codes',{method:'POST',headers:apiHeaders(),body:JSON.stringify({feature:$('#codeFeature').value,expiresInHours:Number($('#codeExpiry').value),maxUses:Number($('#codeUses').value)})});const data=await r.json();if(!r.ok)throw new Error(data.message||'ساخت کد انجام نشد.');const result=$('#codeResult');result.hidden=false;result.innerHTML=`<b>${data.code}</b><button class="secondary-button" id="copyAccessCode">کپی کد</button><small>این کد فقط اکنون نمایش داده می‌شود؛ آن را امن به کاربر برسانید.</small>`;$('#copyAccessCode').onclick=async()=>{try{await navigator.clipboard.writeText(data.code);showToast('کد کپی شد.')}catch{showToast('کپی خودکار در دسترس نیست؛ کد را دستی بردارید.')}};const refreshed=await fetch('/api/admin/access-codes',{headers:apiHeaders(false),cache:'no-store'});const latest=await refreshed.json();$('#accessCodeList').innerHTML=renderAdminCodeRows(latest.codes||[]);bindCodeRevokers();showToast('کد ساخته شد؛ فقط همین بار متن آن نمایش داده می‌شود.')}catch(error){showToast(error.message||'ساخت کد انجام نشد.')}finally{button.disabled=false}};
    bindCodeRevokers();
  }catch(error){showToast(error.message||'بخش مدیریت قابلیت‌ها در دسترس نیست.')}
}
function renderAdminCodeRows(codes){if(!codes.length)return'<div class="empty-codes">هنوز کدی ساخته نشده است.</div>';return codes.map(code=>`<div class="access-code-row"><span><b>${featureLabels[code.features?.[0]]||code.features?.[0]||'—'}</b><small>${code.uses}/${code.maxUses} <span>استفاده</span> · ${new Date(code.expiresAt).toLocaleString(document.documentElement.lang==='fa'?'fa-IR':'en-US')}</small></span><button class="revoke-code" data-revoke-code="${code.id}" ${code.revoked||code.id==='new-code'?'disabled':''}>${code.revoked?'باطل‌شده':'باطل‌کردن'}</button></div>`).join('')}
function bindCodeRevokers(){ $$('[data-revoke-code]:not(:disabled)',modalContent).forEach(button=>button.onclick=async()=>{if(!confirm(document.documentElement.lang==='en'?'Revoke this access code?':'این کد باطل شود؟'))return;try{const r=await fetch(`/api/admin/access-codes/${encodeURIComponent(button.dataset.revokeCode)}`,{method:'DELETE',headers:apiHeaders(false)});const data=await r.json();if(!r.ok)throw new Error(data.message||'ابطال کد ناموفق بود.');button.textContent='باطل‌شده';button.disabled=true;showToast('کد باطل شد.')}catch(error){showToast(error.message||'ابطال کد ناموفق بود.')}})}
async function adminManagementModal(){
  if(!await refreshAuth()){loginModal(()=>adminManagementModal());return}
  try{
    const response=await fetch('/api/admin/settings',{headers:apiHeaders(false),cache:'no-store'});
    if(response.status===401){loginModal(()=>adminManagementModal());return}
    const settings=await response.json();if(!response.ok)throw new Error(settings.message||'تنظیمات مدیریت بارگذاری نشد.');
    const origins=settings.approvedOrigins||[];
    const options=origins.map(origin=>`<option value="${origin}" ${origin===settings.serverOrigin?'selected':''}>${origin}</option>`).join('');
    openModal(`<h2 id="modalTitle">مدیریت سرور و حساب مدیر</h2><p class="modal-subtitle">نام کاربری مدیر ثابت است؛ گذرواژه را می‌توانید تغییر دهید.</p><div class="admin-summary"><span>نام کاربری</span><b>${settings.username}</b><span>اتصال API صرافی</span><b>${settings.exchangeConnectionsEnabled?'فعال در سرور':'غیرفعال در سرور'}</b><span>معاملات واقعی</span><b>${settings.liveTradingEnabled?'فعال':'خاموش'}</b></div><div class="form-group"><label for="serverOrigin">دامنهٔ عمومی / سرور</label><select id="serverOrigin" ${!settings.canChangeServerOrigin?'disabled':''}>${options||'<option value="">دامنه‌ای مجاز نشده</option>'}</select></div><div class="modal-note">می‌توان فقط بین دامنه‌هایی جابه‌جا شد که مدیر سرور از قبل در VEXON_MANAGEABLE_ORIGINS مجاز کرده است. تغییر این فهرست به‌تنهایی DNS، گواهی HTTPS یا reverse proxy را تنظیم نمی‌کند؛ پس از تغییر دامنه، برنامهٔ Android نیز باید با آدرس جدید دوباره ساخته شود.</div><div class="form-row admin-buttons"><button class="secondary-button" id="testServer">آزمون اتصال سرور</button><button class="primary-button" id="saveServer" ${!settings.canChangeServerOrigin?'disabled':''}>ذخیرهٔ دامنه</button></div><button class="secondary-button" id="manageFeatures">قفل قابلیت‌ها و ساخت کد ورود</button><div class="admin-divider"></div><h3>تغییر گذرواژهٔ مدیر</h3><div class="form-group"><label for="currentPassword">گذرواژهٔ فعلی</label><input id="currentPassword" type="password" autocomplete="current-password" /></div><div class="form-group"><label for="newPassword">گذرواژهٔ جدید (حداقل ۱۶ نویسه)</label><input id="newPassword" type="password" autocomplete="new-password" minlength="16" /></div><div class="form-group"><label for="confirmPassword">تکرار گذرواژهٔ جدید</label><input id="confirmPassword" type="password" autocomplete="new-password" minlength="16" /></div><button class="primary-button" id="changeAdminPassword">تغییر گذرواژه و خروج از همهٔ نشست‌ها</button><button class="secondary-button" id="cancelModal">بستن</button>`);
    $('#cancelModal').onclick=closeModal;$('#manageFeatures').onclick=adminFeaturesModal;
    $('#testServer').onclick=async()=>{try{const r=await fetch('/api/health',{cache:'no-store'});const h=await r.json();showToast(r.ok?`سرور پاسخ داد · اتصال صرافی ${h.exchangeConnectionsEnabled?'فعال':'خاموش'}`:'سرور پاسخ معتبر نداد.')}catch{showToast('ارتباط با سرور برقرار نشد.')}};
    $('#saveServer').onclick=async()=>{const serverOrigin=$('#serverOrigin').value;if(!serverOrigin){showToast('دامنهٔ مجاز انتخاب نشده است.');return}try{const r=await fetch('/api/admin/settings',{method:'POST',headers:apiHeaders(),body:JSON.stringify({serverOrigin})});const data=await r.json();if(!r.ok)throw new Error(data.message||'ذخیره انجام نشد.');closeModal();showToast('دامنه ذخیره شد؛ اتصال بعدی را از دامنهٔ جدید انجام دهید.')}catch(error){showToast(error.message||'ذخیرهٔ دامنه انجام نشد.')}};
    $('#changeAdminPassword').onclick=async()=>{const currentPassword=$('#currentPassword').value,newPassword=$('#newPassword').value,confirmPassword=$('#confirmPassword').value;if(newPassword.length<16){showToast('گذرواژهٔ جدید باید دست‌کم ۱۶ نویسه باشد.');return}if(newPassword!==confirmPassword){showToast('تکرار گذرواژه با مقدار جدید یکسان نیست.');return}try{const r=await fetch('/api/auth/change-password',{method:'POST',headers:apiHeaders(),body:JSON.stringify({currentPassword,newPassword})});const data=await r.json();if(!r.ok)throw new Error(data.message||'تغییر گذرواژه انجام نشد.');closeModal();authState={authenticated:false,csrfToken:null};connectedExchanges.clear();renderConnectionStatus();showToast('گذرواژه تغییر کرد؛ برای ادامه دوباره وارد شوید.')}catch(error){showToast(error.message||'تغییر گذرواژه انجام نشد.')}};
  }catch(error){showToast(error.message||'تنظیمات سرور در دسترس نیست.')}
}
function settingsModal(){openModal(`<h2 id="modalTitle">تنظیمات و امنیت</h2><p class="modal-subtitle">${authState.authenticated?'نشست امن فعال است':'برای مدیریت کلیدهای صرافی، وارد حساب سرور شوید.'}</p><div class="settings-list"><label><span><b>مخفی‌کردن موجودی</b><small>پنهان‌سازی مبالغ روی صفحه</small></span><input type="checkbox" id="privacyToggle" ${balanceHidden?'checked':''}></label><label><span><b>تأیید پیش از سفارش</b><small>برای همهٔ سفارش‌های واقعی الزامی است</small></span><input type="checkbox" checked disabled></label><label><span><b>دسترسی برداشت</b><small>کلید API باید بدون مجوز برداشت باشد</small></span><input type="checkbox" disabled></label></div><div class="modal-note">کلیدها در مرورگر ذخیره نمی‌شوند؛ سرور آن‌ها را با AES-256-GCM رمز می‌کند. کلید اصلی رمزنگاری فقط باید در secret manager سرور نگهداری شود.</div><button class="secondary-button" id="authAction">${authState.authenticated?'خروج از حساب':'ورود امن'}</button><button class="secondary-button" id="manageServer">مدیریت سرور و گذرواژه</button><button class="primary-button" id="settingsDone">بستن</button>`);$('#privacyToggle').onchange=()=>{$('#hideBalance').click()};$('#settingsDone').onclick=closeModal;$('#manageServer').onclick=()=>adminManagementModal();$('#authAction').onclick=async()=>{if(!authState.authenticated){loginModal(()=>settingsModal());return}try{await fetch('/api/auth/logout',{method:'POST',headers:apiHeaders(false)});authState={authenticated:false,csrfToken:null};connectedExchanges.clear();renderConnectionStatus();closeModal();showToast('از حساب خارج شدید.')}catch{showToast('خروج از حساب سرور انجام نشد.')}}}
$('#activityFilter').setAttribute('title','دانلود گزارش CSV');$('.notification').onclick=()=>openModal(`<h2 id="modalTitle">اعلان‌ها</h2><p class="modal-subtitle">پیام‌های حساب و وضعیت سرویس</p><div class="notice-item"><span class="notice-dot"></span><div><b>معاملات واقعی غیرفعال است</b><small>پیش از اتصال API، بک‌اند امن باید راه‌اندازی شود.</small></div></div><div class="notice-item"><span class="notice-dot muted-dot"></span><div><b>به Vexon خوش آمدید</b><small>قیمت‌ها و تحلیل‌های فعلی نمایشی هستند.</small></div></div><button class="primary-button" id="noticesDone">متوجه شدم</button>`);$('#noticesDone').onclick=closeModal;
$('.more-btn').onclick=()=>settingsModal();$('.top-avatar').onclick=()=>settingsModal();
$('#assetPicker').onclick=()=>{const keys=Object.keys(assets);let idx=keys.findIndex(k=>assets[k].name===currentAsset);const a=assets[keys[(idx+1)%keys.length]];currentAsset=a.name;$('#chartAsset').textContent=a.name;$('#chartTicker').textContent=a.ticker;$('#chartPrice').textContent=a.price;$('.asset-select .coin-icon').className='coin-icon '+a.cls;$('.asset-select .coin-icon').textContent=a.icon};
$$('.side-nav .nav-item[href],.mobile-nav a').forEach(link=>link.addEventListener('click',()=>{$$('.side-nav .nav-item').forEach(x=>x.classList.remove('active'));if(link.classList.contains('nav-item'))link.classList.add('active');$$('.mobile-nav a').forEach(x=>x.classList.remove('active'));if(link.closest('.mobile-nav'))link.classList.add('active')}));
$('#languageToggle').onclick=()=>window.VexonI18n?.toggle();
loadProviderSupport();
refreshAuth().then(authenticated=>{if(authenticated)loadExchangeStatuses()});
if ('serviceWorker' in navigator && location.protocol.startsWith('http') && !new URLSearchParams(location.search).has('native')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
